---
title: "Doing Data Science - Case Study 01"
author: "Adeel & Amita"
date: "October 13, 2018"
output: html_document
---

## CASE STUDY 01 - October 18

### Description

The Beers dataset contains a list of 2410 US craft beers and Breweries dataset contains 558 US breweries. The datasets descriptions are as follows
t

```{r}

library('dplyr')
library('ggplot2')

Breweries <- read.csv("Breweries.csv")
Beers <- read.csv("Beers.csv")

# Rename the coolumn name

names(Breweries)[2] <- 'Brewery Name'

names(Beers)[1] <- 'Beer Name'

```

```{r}

data <- Breweries %>% group_by(State) %>%
    summarize(Count = n())

ggplot(data, aes(State, Count, label = Count)) + 
    geom_bar(stat = "identity", width = .85, fill=rainbow(51)) +
      theme(axis.text.x = element_text(angle=90, vjust=0.6), plot.title = element_text(hjust = 0.5))+
  geom_text(size = 2.5, position = position_stack(vjust = 1.08))


```


```{r}

# Merge beer data with the breweries data. Print the first 6 observations and the last six observations to check the merged file.

MergedData <- merge(Beers, Breweries, by.y = 'Brew_ID', by.x = 'Brewery_id')

head(MergedData[,c('Beer Name', 'ABV', 'IBU', 'Style', 'Brewery Name', 'City', 'State')])

tail(MergedData[,c('Beer Name', 'ABV', 'IBU', 'Style', 'Brewery Name', 'City', 'State')])

#data <- tidyr::unite(MergedData, 'Location', c(City, State), remove=FALSE, sep=", ")
#View(MergedData[c(1:6,2405:2410),c('Beer Name', 'ABV', 'IBU', 'Style', 'Ounces', 'Brewery Name', 'City', 'State')])


```


```{r}

# 3.	Report the number of NA's in each column.

data <- sapply(MergedData[!complete.cases(MergedData),],
       function(y) length(which(is.na(y))))

View(data)


```


```{r}

# 4.	Compute the median alcohol content and international bitterness unit for each state. 
#     Plot a bar chart to compare.

MergedData.Median <-  MergedData[complete.cases((MergedData)),] %>% # Find all the data  without NA's in it.
    group_by(State) %>%                         # Group by data frmae by state
    dplyr::summarise(ABV = median(ABV), IBU = median(IBU))  # Summary that data to find out median for ABV and IBU


p1 <- ggplot2::ggplot(MergedData.Median, aes(State, IBU, fill=IBU)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle=90, vjust=0.6), plot.title = element_text(hjust = 0.5)) 

p2 <- ggplot2::ggplot(MergedData.Median, aes(State, ABV, fill = ABV)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle=90, vjust=0.6), plot.title = element_text(hjust = 0.5))


p1
p2
#ggpubr::ggarrange(p1, p2)

```

```{r}

# 5. Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer?

ABV.Max <- MergedData[which.max(MergedData$ABV),]
IBU.MostBitter <- MergedData[which.max(MergedData$IBU),]

data.frame('Maximum_Alcoholic_Beer' = ABV.Max$State, 'ABV Max' = ABV.Max$ABV, 't' = IBU.MostBitter$State, 'IBU Most' = IBU.MostBitter$IBU)

```



```{r}

# 6.	Summary statistics for the ABV variable. ????

summary(MergedData)

```


```{r}

# 7.	Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot.


MergedData.Median
#ggplot2::ggplot(df, aes(x = State,y = value, fill = variable)) +   geom_point(stat = "identity")

plot(MergedData$IBU, MergedData$ABV, pch = 148, col = c('Red', 'Green'), 
     xlab = "I B U", ylab = "A B V", main = "IBU vs ABU chart")

```


```{r}

# 

```








